# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/kzhan/DATA/Desktop/SUTD/Term_4/50.002-Comstruc Spring 2026/alchitry/20mhz/cores/clk_wiz_various/clk_wiz_various.xci
# IP: The module: 'clk_wiz_various' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kzhan/DATA/Desktop/SUTD/Term_4/50.002-Comstruc Spring 2026/alchitry/20mhz/cores/clk_wiz_various/clk_wiz_various_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_various'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/kzhan/DATA/Desktop/SUTD/Term_4/50.002-Comstruc Spring 2026/alchitry/20mhz/cores/clk_wiz_various/clk_wiz_various.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_various'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/kzhan/DATA/Desktop/SUTD/Term_4/50.002-Comstruc Spring 2026/alchitry/20mhz/cores/clk_wiz_various/clk_wiz_various_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_various'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/kzhan/DATA/Desktop/SUTD/Term_4/50.002-Comstruc Spring 2026/alchitry/20mhz/cores/clk_wiz_various/clk_wiz_various.xci
# IP: The module: 'clk_wiz_various' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kzhan/DATA/Desktop/SUTD/Term_4/50.002-Comstruc Spring 2026/alchitry/20mhz/cores/clk_wiz_various/clk_wiz_various_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_various'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/kzhan/DATA/Desktop/SUTD/Term_4/50.002-Comstruc Spring 2026/alchitry/20mhz/cores/clk_wiz_various/clk_wiz_various.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_various'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/kzhan/DATA/Desktop/SUTD/Term_4/50.002-Comstruc Spring 2026/alchitry/20mhz/cores/clk_wiz_various/clk_wiz_various_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_various'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
